### ISSUE TITLE
Add mDNS support for local networks

### ISSUE THREAD

**Issue by techryda** [ukanth/afwall#326]
When I enable "LAN control" on my Android device I cannot send out mDNS requests.  mDNS broadcasts go to 224.0.0.251 on UDP port 5353.  This request stays within the local network and, I believe, should be allowed.  It's useful for printer and device discovery.

My request is that this address range would be allowed/whitelisted when I enable 'LAN communication' for one of my apps.

More info on mDNS can be found at: https://en.wikipedia.org/wiki/Multicast_DNS

Thanks for your time developing this program.

**Comment by lpinner** [comment]
Another use case is apps that only have LAN enabled are unable to discover dlna media servers on the LAN. I assume most users regardless of their technical abililities would expect enabling LAN access for an app would allow that app to find their media server on tje LAN. I use a custom script to allow multicast but not all users would be able to figure that out.

**Comment by CHEF-KOCH** [comment]
Thanks for all the input, now I know what you guys want. I'm not very familiar with mdns but as far as I know not all kernels/netd including mdns support [only Android OS 4.1+ adds native Bonjour/Zeroconf support - I think _CONFIG_IP_MULTICAST_ for example]. Maybe _netstat -g_ , _/proc/net/igmp_ or _ip maddr show_ can show if we have support.

And after some research:
* https://android.googlesource.com/platform/external/mdnsresponder/
* http://developer.android.com/training/connect-devices-wirelessly/nsd.html (Android 4.1 - NSD)
* http://cafbit.com/entry/testing_multicast_support_on_android (see also last 30 interesting comments -> IGMP packages != maybe not sent via multicast according to wikipedia)

There also some other troubles with it [mdns/nds), see also [#19550](https://code.google.com/p/android/issues/detail?id=19550), [#73466](https://code.google.com/p/android/issues/detail?id=73466&q=mdns&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars), [#35585](https://code.google.com/p/android/issues/detail?id=35585), [#39583](https://code.google.com/p/android/issues/detail?id=39583), [#39750](https://code.google.com/p/android/issues/detail?id=39750)

If I try <code>ifconfig eth0 multicast</code> to enable and <code>ifconfig eth0 -multicast</code> to disable it, it shows that I don't have any multicast present in the interface.

Conclusion:
So this is definitely not for all people. But if a smart person have any script to get this working (on devices which definitely have multicast support) he can leave it here and I add this into our FAQ.

**Comment by lpinner** [comment]
http://en.m.wikipedia.org/wiki/Multicast_address

$IPTABLES -A "afwall-wifi" --destination "224.0.0.0/24" -j RETURN || exit

**Comment by CHEF-KOCH** [comment]
Thanks.

There are also several other multicasts addresses available, like:
224.0.0.1 - all hosts on this subnet
224.0.0.2 - all routers on this subnet
224.0.0.5 - Open Shortest Path First (OSPF) Version 2, designed to reach all OSPF routers on a network
224.0.0.6 - OSPF Version 2, designed to reach all OSPF designated routers on a network
224.0.0.9 - Routing Information Protocol (RIP) Version 2
224.0.1.1 - Network Time Protocol
.....

I may add an separate category in the wiki about mdns/NSD.

**Comment by techryda** [comment]
From a cursory exploration of http://en.m.wikipedia.org/wiki/Multicast_address

it seems that the following:

224.0.0.1 - all hosts on this subnet
224.0.0.251 - Multicast DNS (mDNS) address
224.0.0.252 - Link-local Multicast Name Resolution (LLMNR) address

are the main addresses to be concerned with.
I would not do a blanket ALLOW for 224.0.0.0/24 because some of these addresses
route outside of the local network and this IS a firewall app.

**Comment by lpinner** [comment]
I thought 224.0.0.1-255 was local subnet only:

"Addresses in the range of 224.0.0.0 to 224.0.0.255 are individually assigned by IANA and designated for multicasting on the local subnetwork only. <snip> Routers must not forward these messages outside the subnet in which they originate."

But that was just from Wikipedia which I wouldn't rely on.

**Comment by CHEF-KOCH** [comment]
This issue is obsolete since it is integrated in Chrome and not Android itself, see [#405925](https://code.google.com/p/chromium/issues/detail?id=405925). It's also marked as _obsolete_ in my mentioned issue report [#19550](https://code.google.com/p/android/issues/detail?id=19550). Google forces the user to use network service discovery (NSD) and since Android 5 mDNS .

If your ROM does [support it](https://android.googlesource.com/platform/external/mdnsresponder/) you need to do it yourself via custom script. 

The API can be found over here:
* http://developer.android.com/training/connect-devices-wirelessly/nsd-wifi-direct.html
* http://developer.android.com/reference/android/net/nsd/NsdManager.html

**Comment by afflux** [comment]
I get lots of toats about AFWall blocking mDNS requests in some circumstances on CM12.1 2015-11-02. The requests originate from mdnsd (from mdnsresolver), which is started from NsdService. What do you suggest?

**Comment by CHEF-KOCH** [comment]
Yes since 5 we got mdns but you only see such toasts if there is something specific enabled for it, e.g. F-Droid supports mdns to share the apk's over local network. Android itself not use it by default due security reasons. So we need additional infos, to say xyt spams such a requests without anything doesn't help.

**Comment by afflux** [comment]
Unfortunately, I don't see how to debug which app is causing the NsdService to enable.

**Comment by sir-brickalot** [comment]
I'm on CM12.1.1-20151106 (Xposed+Xprivacy) and AFWall+ 2.1.1. and lately I get tons of toasts like `AFwall+ Blocked : null(1020)-224.0.0.251:5353`. Unfortunately I don't know how to _allow_ this process in AFwall.  
The Log says:

```
AppID : -11
Application's Name: 
Total Packets Blocked:  243
[UDP]224.0.0.251:5353(243)
```

AppID -11 is the Linux Kernel and everything is whitelisted for this process.

So is there a workaround or a possible fix, or an fault on my side?

**Comment by CHEF-KOCH** [comment]
You should ask the CM team why it requests for it which makes not much sense. I guess this is coming from the new 'sharing' function.

**Comment by sir-brickalot** [comment]
That is why we use firewalls, right? But it still bugs me that I whitelisted everything for the process but these packets get blocked anyways. I don't get why the CM team should be asked (except why they implemented it). The main problem here as I see it is that AFWall doesn't comply with the rules that have been set.  
Or am I misunderstanding something here?  

/Update: I tried the AFWall Notification Filter and even ticking ALL apps and processes, the mentioned notification still pops up. This is another indicator that something is wrong with AFWall or my local installation.

[Link to afwall_rules.log.txt](https://dl.dropboxusercontent.com/u/69390952/afwall_rules.log.txt) on dropbox

**Comment by CHEF-KOCH** [comment]
The mDNS source is available over [here](https://github.com/CyanogenMod/android_external_mdnsresponder/tree/cm-10.2/mDNSPosix) which also explains how it works. As explained over [this document](https://github.com/CyanogenMod/android_external_mdnsresponder/blob/cm-10.2/PrivateDNS.txt) it acts like a DNS firewall if dnsextd is in usage, which overall means it listening on DNS TCP/UDP port 53 all the time to determinate which zone is currently in usage. Which means it makes no sense to block this, but you can play with the configuration (example is also given) but's depending on how it was implemented in your ROM. 

So I suggest we possible whitelist this in general.

**Comment by sir-brickalot** [comment]
Thank you @CHEF-KOCH for the explanation. Unfortunately I'm not experienced enough to "play with the configuration".
I would be grateful if you could post a Custom Script to circumvent this problem.

Maybe I'm not capable enough to understand your explanation but does it actually explain, why I can't control the blocking of mdns via AFWall GUI?

**Comment by ghost** [comment]
I'm having this issue too, "Linux kernel" is whitelisted and LAN control is disabled. The notifications are really annoying.

**Comment by CHEF-KOCH** [comment]
I suggest to not block the Kernel since this breaks possible too many internal things without any benefit. I also never saw any attack or unloved traffic on this since Lollipop, so maybe we need to rework the 'unknown traffic' switch.

**Comment by ionum** [comment]
Added support for localnet multicast adresses (ipv4 and ipv6) https://github.com/ukanth/afwall/pull/620

**Comment by hackel** [comment]
Why is UID 1020 (AID_MDNSR 1020 /* MulticastDNSResponder (service discovery) */) not available in the app list to allow/deny explicitly?  I'm trying to get the Android TV remote app to work which uses mDNS without much luck.

**Comment by hackel** [comment]
Why is UID 1020 (AID_MDNSR 1020 /* MulticastDNSResponder (service discovery) */) not available in the app list to allow/deny explicitly?  I'm trying to get the Android TV remote app to work which uses mDNS without much luck.

**Comment by michaelh99** [comment]
I'm also seeing a lot of alerts for mDns being blocked but it doesn't show up in the afwall list of processes

**Comment by linkp** [comment]
I'm seeing these notifications as well. It appears to be the Facebook app triggering these mdns packets. While I am quite content to have the traffic denied, without an entry on the app list, it makes blocking the notification spam impossible without disabling all notifications.

Getting an entry for UID 1020 onto the app list would be useful in suppressing the noise, as well as a benefit for the users who are using mdns in their networks that wold like to permit the traffic.

**Comment by Gitoffthelawn** [comment]
Why is the Facebook app triggering these mDNS packets?

**Comment by linkp** [comment]
I have no idea why the Facebook app is causing the Android to generate mDNS traffic under UID 1020. Searches for Facebook Androidp app and mDNS were fruitless. I don't currently use mDNS from my Android, so I am content to let AWFall+ block it, but it would be nice to be able to disable the barrage of notifications AFWall+ is generating without resorting to disabling all AFWall+ block notifications. Until UID 1020 appears in the application list, or more specifically, the notification suppression list, I'm left with only two unsatisfactory options.

**Comment by minteral** [comment]
I'm also looking for a solution to suppress the blocked mdns package notifications.

**Comment by ionum** [comment]
This should be resolved by #620. @ukanth, i think you can close this issue ....

**Comment by ukanth** [comment]
@ionum 

Not really, I was expecting issues since all the devices/iptables are not same. That's the reason I wanted to separate it from core.

already reported failure.
https://forum.xda-developers.com/showpost.php?p=71025484&postcount=3649

I might revert the change and work on my alternate approach

**Comment by gerroon** [comment]
I have the same issue @hackel has. I get toasts about 1020 mdns but mdns is not listed in the appss nor 1020 process.

**Comment by mirfatif** [comment]
+1 for issue reported by @hackel and @gerroon.
```
mDNS(1020)
Source: 192.168.43.1:5353
Destination: 224.0.0.251:5353
Protocol: UDP
```
Multiple requests being denied per second. UID 1020 not listed in apps list. Devices connected over Wi-Fi tethering can't resolve host.

**Comment by internationils** [comment]
Also seeing this... same destination 224.0.0.251:5353. This is (on my side) caused by the Beoplay app, which is trying to find and connect to the speaker (connected via bluetooth).
Strange thing is that even if I disable or even (force) close afwall, the speaker still isn't found.
Is this an AFwall issue, an AFwall notification issue, or a ROM issue?

**Comment by CHEF-KOCH** [comment]
mDNS request are never caused by one app, the app simply starts a daemon which 'floods' you with those messages the only way to prevent this is to block the deamon or restrict it. mDNS itself is by default enabled in every OS no matter if Android, Windows or Linux.

One way would be to disallow mDNS via your router which also stops your router from leaking LAN traffic to the WAN. Most newer firmwares already have a implementation for this integrated to prevent leaks or spoofing. [Switching loop](http://www.omnisecu.com/cisco-certified-network-associate-ccna/what-is-layer-2-switching-loop.php) is also network 'created' issue. You usually can see what is started via: `lsof -n -i | grep 5353` or `lsof -i :5353` indentify which process runs it and then check your network configuration because blocking the application doesn't stop that something is flooding it, I know several switches, adapters or network configuration do this.

ukanth can't fix anything here because it's not an app issue. It's also not a ROM issue because as explained the ROM itself doesn't spawn the deamon process as long something doesn't requests it. Typically you only see listening which is okay.

**Comment by chrcoluk** [comment]
fe80 should never be blocked really, I think I will examine the rules created by afwall to see what standards are been broken.

Right now with all boxes ticked on kernel, and mdns also allowed on both wifi and lan I get mdns been blocked as well as icmp, icmp is a nasty one as well as icmp is important for mtu discovery.

The solution to this problem is allow rules for the following. (bypass app restrictions).

Allow icmp6 types timex, toobig, unreach, paramprob globally
Allow icmp types times,unreach globally
Allow all fe80::/10 for src and dst globally
Allow icmp6 types neighboradv, neighborsol, routeradv, routersol to dst ff02::/16

I will make a custom script for this which maybe could be added to the wiki.

**Comment by gerroon** [comment]
@chrcoluk 

Please paste it here when you have a working one.

**Comment by ukanth** [comment]
You can add mDNS from list of apps to whitelist (LAN access should be least) in 3.2.0

**Comment by gerroon** [comment]
I do not have mdns listed, on LIneageOs 7.1 using 3.1 from Fdroid
